"""add_mark_column_to_maintance

Revision ID: 03094631a120
Revises: d7dd274d1fc6
Create Date: 2025-10-15 20:12:47.608104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '03094631a120'
down_revision: Union[str, None] = 'd7dd274d1fc6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('maintance', sa.Column('mark', sa.Boolean(), nullable=True))

    # Update existing rows to have a default value
    op.execute("UPDATE maintance SET mark = 0 WHERE mark IS NULL")

    # Now alter the column to be NOT NULL
    with op.batch_alter_table('maintance') as batch_op:
        batch_op.alter_column('mark', existing_type=sa.Boolean(), nullable=False)


# ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('maintance', 'description',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('maintance', 'mileage',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.drop_column('maintance', 'mark')
    # ### end Alembic commands ###
